# Generated by Django 3.2 on 2022-04-16 16:41

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0002_user_model_extend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 4, 18, 16, 41, 48, 575762, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
