# Generated by Django 3.2 on 2022-04-17 18:11

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0006_create_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 4, 19, 18, 11, 13, 409049, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
