# Generated by Django 3.2 on 2022-04-25 16:58

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0007_alter_shopuser_activation_key_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 4, 27, 16, 58, 55, 923902, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
